# Generated by Django 4.1.13 on 2024-04-16 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('horas_conferencias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Conferencia')),
                ('horas_cp', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Clase Practica')),
                ('horas_cpc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Clase Practica Computadoras')),
                ('horas_lab', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Laboratorio')),
                ('horas_taller', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Taller')),
                ('horas_seminarios', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Seminario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('apellidoPaterno', models.CharField(max_length=35)),
                ('apellidoMaterno', models.CharField(max_length=35)),
                ('nombres', models.CharField(max_length=35)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('vigencia', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.SlugField(default='')),
                ('carrera', models.CharField(default='', max_length=50)),
                ('anno', models.SlugField(verbose_name='Año del grupo')),
                ('curso', models.DateTimeField(blank=True, null=True)),
                ('curso_f', models.DateTimeField(blank=True, null=True)),
                ('semestre', models.CharField(default='', max_length=50)),
                ('tipo_curso', models.CharField(choices=[('diurno', 'Diurno'), ('encuentro', 'Encuentro'), ('distancia', 'Distancia'), ('ciclo_corto', 'Ciclo_corto')], max_length=50)),
                ('nombre', models.CharField(blank=True, default='', max_length=255)),
                ('horas_conferencias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Conferencia')),
                ('horas_cp', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Clase Practica')),
                ('horas_cpc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Clase Practica Computadoras')),
                ('horas_lab', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Laboratorio')),
                ('horas_taller', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Taller')),
                ('horas_seminarios', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Horas Seminario')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('movil', models.IntegerField(blank=True, null=True)),
                ('categoria_doc', models.CharField(max_length=50)),
                ('categorias_cientificas', models.CharField(max_length=50)),
                ('responsabilidad', models.CharField(default='', max_length=250)),
                ('tipo_relacion', models.CharField(choices=[('completo', 'Completo'), ('contrato', 'Contrato'), ('colaborar', 'Colaborar')], max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.asignatura')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.plan_estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.asignatura')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.plan_estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.plan_estudio')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.profesor')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.events')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.disciplina')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='plan_estudio',
            name='profesores',
            field=models.ManyToManyField(through='article.Relacion2', to='article.profesor'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaMatricula', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='profesores',
            field=models.ManyToManyField(through='article.Relacion1', to='article.profesor'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='profesores',
            field=models.ManyToManyField(through='article.Relacion', to='article.profesor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.profesor'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=100)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.profesor')),
            ],
        ),
    ]
